### ISSUE TITLE
tangy-gui-coincidence-counter, cannot import name 'find_delay' from 'tangy'

### ISSUE THREAD

**Issue by FarisRedza** [Peter-Barrow/tangy#2]
**Describe the bug**
Import error from running `tangy-gui-coincidence-counter`

**To Reproduce**
Running `tangy-gui-coincidence-counter` results in
```
Traceback (most recent call last):
  File "/home/jh115/python-venvs/pythona/bin/tangy-gui-coincidence-counter", line 5, in <module>
    from tangy.apps.gui_coincidence_counter import run
  File "/home/jh115/python-venvs/pythona/lib/python3.10/site-packages/tangy/apps/gui_coincidence_counter.py", line 12, in <module>
    from tangy import find_delay
ImportError: cannot import name 'find_delay' from 'tangy' (/home/jh115/python-venvs/pythona/lib/python3.10/site-packages/tangy/__init__.py)
```

**System (please complete the following information):**
 - Ubuntu
 - 22.04

**Additional context**
Commenting out the import of `find_delay` in `gui_coincidence_counter.py` seems to fix this and the window shows up, has `find_delay` been deprecated?

**Comment by Peter-Barrow** [comment]
```find_delay``` has been deprecated and replaced with ```buffer.relative_delay```, this should be resolved in c6d7a2a. A new revision 0.5.2 has been pushed to PyPi
