### ISSUE TITLE
Tangy is incompatible with Numpy 2.0

### ISSUE THREAD

**Issue by FarisRedza** [Peter-Barrow/tangy#4]
**Describe the bug**
When installing tangy, the latest version of numpy is installed, which is currently version 2.0.0, but this version is incompatible with tangy since there are breaking changes compared to version 1.26.4. Reverting back to numpy 1.26.4 solves this.

**To Reproduce**
Install tangy with pip without specifying numpy version

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by Peter-Barrow** [comment]
Updated to Numpy 2.0, see 7a6094a, new minor revision v0.5.4 now available on PyPi
