### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by fbbarnes** [Peter-Barrow/tangy#5]
Could not install on macOS (Apple Silicon) following readme.
System (please complete the following information):
 - OS: MacOS
 - Version 14.3

Additional context

Manually cloned git from GitHub via https. 
Made changes to platform ifdefs to include macOS (see file attached).
Now builds and loads .ptu files. 
[shared_memory copy.txt](https://github.com/user-attachments/files/16637903/shared_memory.copy.txt)

**Comment by Peter-Barrow** [comment]
Thanks for reporting this.

macOS support is now added (e009f81), latest release v0.7.0 is available from PyPi

**Comment by fbbarnes** [comment]
Works great cheers! Just have to ensure correct version of Python (3.10 working for me) is installed - may be worth documenting this somewhere?

**Comment by Peter-Barrow** [comment]
Could you check if it installs in different Python version please, it should be being built for the following versions:
https://github.com/Peter-Barrow/tangy/blob/e009f816395d5af9c8a1e0cafc5475fe1d2ca418/pyproject.toml#L76-L91

**Comment by fbbarnes** [comment]
Works on cp39-macosx_arm64, cp310-macosx_arm64, and cp311-macosx_arm64. I was using cp312-macosx_arm64 when I ran into problems but see now that Python 3.12 is not supported on macos. Thank you!

**Comment by Peter-Barrow** [comment]
Great news, now I don't have to look at the CI
