### ISSUE TITLE
crash when zero coincidences

### ISSUE THREAD

**Issue by Thomas-Jaeken** [Peter-Barrow/tangy#9]
[this line](https://github.com/Peter-Barrow/tangy/blob/d09b872f9a1cc8278fabf96c07fc9331fab14dab/tangy_src/_tangy.py#L767) makes it crash when there are no coincidences which is not ideal, instead it should just return the count as 0.

**Comment by Peter-Barrow** [comment]
Change made [here](https://github.com/Peter-Barrow/tangy/blob/591958a479d0b2a2527a157583412421178dfbe9/tangy_src/_tangy.py#L1098) should now stop this happening. ```buffer.coincidence_collect(...)``` will now provide a warning if its run and no coincidences are found
``` python
if count == 0:
    warnings.warn("No coincidences found")
    return None
```

Available in v0.9.1, update through pip
